### ISSUE TITLE
remove-recipient is not working

### ISSUE THREAD

**Issue by chr4** [oleiade/trousseau#165]
Removing a recipient from trousseau doesn't work (using gpg-agent, tested with multiple trousseau stores)

``` shell
$ trousseau remove-recipient john@example.com
Error: The following keys could not be found in the public keyring: 
```

I'm using the current HEAD in develop.

**Comment by jd1123** [comment]
@chr4 - 

I don't seem to have this problem using the develop branch. Can you post any more information about this bug?

**Comment by chr4** [comment]
This has something very hard to debug.
I'm not entirely sure where the problem lies. In some other stores, it displays the ID of the key, instead of the associated email address, and I can't remove it either.

It's not entirely not possible to remove keys from the recipient list, but it seems that sometimes you can't if the reference is somehow broken.

I realize that this might not be very useful, if I come across any deeper insights, I'll post again :)
Maybe it just "goes away" in some future release. I hope.

**Comment by oleiade** [comment]
Will investigate :-)
