### ISSUE TITLE
Debian jessie apt install problem

### ISSUE THREAD

**Issue by samlinux** [oleiade/trousseau#172]
Hi,
i tried to install trousseau via apt, but
OS: Jessie 

after
echo "deb http://dl.bintray.com/oleiade/deb /" | sudo tee /etc/apt/sources.list.d/trousseau.list
and 
apt-get update

I got the following error:

> E: Problem parsing dependency Depends
> E: Error occurred while processing trousseau (NewVersion2)
> E: Problem with MergeList /var/lib/apt/lists/dl.bintray.com_oleiade_deb_Packages
> E: The package lists or status file could not be parsed or opened.

Any ideas whats going wrong?

**Comment by oleiade** [comment]
Thanks for the report @samlinux 

Gonna look into it as soon as I get access to a debian VM :)

**Comment by samlinux** [comment]
Hi, got you access to a debian vm box?

**Comment by oleiade** [comment]
I confirm I experience the same in Jessie. I think it might be related to bintray, who provides deb packages storage.

Trying to figure out what's wrong :)

**Comment by oleiade** [comment]
Hey @samlinux

It look a lot more time than I would have thought, but my nightmare is finally over: it should work properly on debian based systems again.
Please update your `/etc/apt/sources.list.d/trousseau.list` so the url of the repo is in *https*

Published a new version `0.3.6` which should work properly!
