### ISSUE TITLE
Add a global --no-interactive option

### ISSUE THREAD

**Issue by oleiade** [oleiade/trousseau#179]
In order to ease the automation of trousseau operations, adding a `--no-interactive` global option would make sense. That way, there are no cases where trousseau is expecting input, which could be problematic when ran through a script and might lead to confusion.
With a `--no-interactive` option, whether the command succeeds or fails, but there are no hangs anymore.

``` bash
$ trousseau -s ~/vault keys
Passphrase:
abc: 123
easy as: do re mi

$ trousseau -s ~/vault --no-interactive keys
fatal: couldn't find any passphrase

$ set -x TROUSSEAU_PASSPHRASE 'bla'
$ trousseau -s ~/vault --no-interactive keys
abc: 123
easy as: do re mi
```

**Comment by matm** [comment]
Instead of using `--no-interactive`, isn't looking at the env variable `TROUSSEAU_PASSPHRASE` the default behaviour? What would be the added value of adding `--no-interactive`?
