### ISSUE TITLE
Makefile not present

### ISSUE THREAD

**Issue by sthagen** [oleiade/trousseau#199]
In neither branch I detected a Makefile. Build from source instructions in README.md suggest calling `make`. So, I kindly suggest to either provide a `Makefile` or adapt the documentation to bare `go tool` calls. Same holds for the contributing guidelines.

**Comment by oleiade** [comment]
Hey Stefan, thanks for pointing that out. You are right, the instructions are outdated on that front. I will update it.

**Comment by oleiade** [comment]
Fixed by https://github.com/oleiade/trousseau/commit/5cef7535f5937e894ecc8ac6d1de2fd682571eb7
